package se.lexicon.workshopjpa.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

@EqualsAndHashCode //generates equals and hashcode methods automatically
@ToString //autogenerated toString method
@NoArgsConstructor //generates a no-args constructor
@AllArgsConstructor //generates a constructor with all fields
@Setter //generates setters for all fields
@Getter //generates getters for all fields
@Entity
public class Author {

    //fields
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //generates an id with autoincrement for each entity
    @Setter(AccessLevel.NONE)
    private int id;
    @Column(nullable = false, length = 100)
    private String firstName;
    @Column(nullable = false, length = 100)
    private String lastName;

    @ToString.Exclude
    @ManyToMany(mappedBy = "authors")
    private Set<Book> writtenBooks = new HashSet<>();

    //constructor
    public Author(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    //todo test methods
    //helper methods
    public void addBook(Book book){
        writtenBooks.add(book);
        book.getAuthors().add(this);
    }

    public void removeBook(Book book){
        writtenBooks.remove(book);
        book.getAuthors().remove(this);
    }


}
