package se.lexicon.workshopjpa.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@EqualsAndHashCode //generates equals and hashcode methods automatically
@ToString //autogenerated toString method
@NoArgsConstructor //generates a no-args constructor
@AllArgsConstructor //generates a constructor with all fields
@Setter //generates setters for all fields
@Getter //generates getters for all fields
@Entity //makes this class an entity in the IoC container
public class BookLoan {

    //fields
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //generates an id with autoincrement for each entity
    @Setter(AccessLevel.NONE)
    private int id;
    @Column(nullable = false)
    private LocalDate loanDate;
    @Column(nullable = false)
    private LocalDate dueDate;
    private boolean returned;

    @ManyToOne
    private AppUser borrower;

    @ManyToOne
    private Book book;

    //constructor
    public BookLoan(AppUser borrower, Book book) {
        this.loanDate = LocalDate.now();
        this.dueDate = LocalDate.now().plusDays(book.getMaxLoanDays());
        this.borrower = borrower;
        this.book = book;
    }

}
