package se.lexicon.workshopjpa.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;


@ToString //autogenerated toString method
@NoArgsConstructor //generates a no-args constructor
@AllArgsConstructor //generates a constructor with all fields
@Getter //generates getters for all fields
@Entity //makes this class an entity in the IoC container
public class Book {

    //fields
    @Id //makes id the primary key in Database
    @GeneratedValue(strategy = GenerationType.IDENTITY) //generates an id with autoincrement for each entity
    private int id;
    @Column(nullable = false, length = 100, unique = true) //limits isbn to 100 chars, and makes sure its unique and not null
    private String isbn;
    @Column(nullable = false, length = 100, unique = true) //limits title to 100 chars, and makes sure its unique and not null
    private String title;
    @Column(nullable = false)
    private int maxLoanDays;

    @ManyToMany
    @JoinTable(
            name = "books_authors",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "author_id")
    )
    private Set<Author> authors = new HashSet<>();

    //constructor
    public Book(String isbn, String title, int maxLoanDays) {
        this.isbn = isbn;
        this.title = title;
        this.maxLoanDays = maxLoanDays;
    }
}
